name: tatware
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  equatable: ^2.0.5
  dio: ^4.0.6
  shared_preferences: ^2.0.15
  flutter_screenutil: ^5.5.4
  fluttertoast: ^8.1.1
  dartz: ^0.10.1
  flutter_bloc: ^8.1.1
  get_it: ^7.2.0
  flutter_spinkit: ^5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/icons/

  fonts:
    - family: CairoBold
      fonts:
        - asset: assets/Fonts/Cairo-Bold.ttf
    - family: CairoRegular
      fonts:
        - asset: assets/Fonts/Cairo-Regular.ttf
